### ISSUE TITLE
Closing Qt-Sesam does not stop the task

### ISSUE THREAD

**Issue by Wikinaut** [ola-ct/Qt-SESAM#85] opened 2015-10-16 21:59 UTC
When closing the Qt-Sesam window, or via "Datei > Beenden", the task keeps running.

how to repoduce:
- start Qt-SESAM/Qt-SESAM in a Terminal window
- close Qt-SESAM via "Datei > Beenden"

Terminal: requires now Cntrl+C to kill the task.

**Comment by 607011** [comment] 2015-10-17 05:24
Doesn't happen on 
- Linux (Ubuntu 15.04, 64 bit, running in VMware Player 12).

Tested with 7634d6bde846c2d28ba3add8505b1f3dce8e9e3a

**Comment by 607011** [comment] 2015-10-29 08:30
Closing this issue because it hasn't happened on any platform tested with.

**Comment by Wikinaut** [comment] 2015-11-14 19:35
problem still present (version b927b356501c3b95e34029515060b6de0a2fdeb0 )

**Comment by 607011** [comment] 2015-12-05 15:10
@Wikinaut @pinae Should be fixed in HEAD. Confirmed?

**Closed as completed** 2015-12-05 15:11 UTC

**Comment by Wikinaut** [comment] 2015-12-06 18:26
Yep: confirmed!

**Comment by 607011** [comment] 2015-12-06 18:27
Thanks for testing, @Wikinaut

**Comment by Wikinaut** [comment] 2015-12-06 18:27
What exactly caused this problem?

**Comment by 607011** [comment] 2015-12-06 18:32
To say it with words of Thomas de Mazière: "Ein Teil der Antwort könnte Sie verunsichern." ;-)

**Comment by Wikinaut** [comment] 2015-12-06 18:33
Hehe. Back door in your HEISE code?

**Comment by 607011** [comment] 2015-12-06 18:38
The unsettling part of the answer is: I do not really know what exactly caused the problem.

There must have been some problem in the code that prepared the exit. This code changed in the course of implementing the replacement for the single instance detection (see commit dedb90f601e11c85aa3020ea21e6bc4e357cde4f for instance).

**Comment by Wikinaut** [comment] 2015-12-06 18:40
ok.
