### ISSUE TITLE
Crash on Ubuntu 15.10 (probably due to code flow when another instance has been detected)

### ISSUE THREAD

**Issue by pinae** [ola-ct/Qt-SESAM#92] opened 2015-11-04 19:01 UTC
![qtsesam_error](https://cloud.githubusercontent.com/assets/1160927/10948613/bd8b1dec-832e-11e5-8919-d0671ee090e0.png)

**Comment by 607011** [comment] 2015-11-04 19:03
What did you do? Which version of Qt-SESAM did you use?

**Comment by pinae** [comment] 2015-11-04 19:08
I tried to start QtSESAM and an error message showed up saying that it is already running (which it wasn't). I clicked the message away and got the crash message.

I pulled from master yesterday.

**Comment by 607011** [comment] 2015-11-04 19:11
Yesterday? Mmmmh. What's the hash of the latest commit?

**Comment by 607011** [comment] 2015-11-04 19:11
Please refer to #72 and #82.

**Comment by pinae** [comment] 2015-11-04 19:14
commit 038546fd7058bb00872fe54daef021ab87d35cfb
Author: Oliver Lau ola@ct.de
Date:   Tue Nov 3 17:39:20 2015 +0100

```
Deleted some reminiscences of the recently removed smart login feature.
```

**Comment by pinae** [comment] 2015-11-04 19:18
`--force-start` worked as expected. I could not reproduce the crash.

**Comment by 607011** [comment] 2015-11-05 05:37
OK, then the crash was probably due to the code flow after Qt-SESAM detected the shared memory segment of another instance.

**Comment by 607011** [comment] 2015-11-29 09:23
Qt-SESAM uses a shared memory segment to determine whether or not another instance is running. Unfortunately, if Qt-SESAM crashes prematurely for some reason, this memory segment survives the crash on Linux, preventing further starts.

**Solution**: Qt-SESAM should use a lock file instead of a shared memory segment to detect if another instance is already running. Lock files can easily be removed and do not require a reboot.

**Comment by 607011** [comment] 2015-11-29 09:23
Yay! There's even a class for this purpose: `QLockFile`.

**Comment by 607011** [comment] 2015-12-05 12:05
Working on this issue in branch 'LockFile-Dev'.

**Comment by 607011** [comment] 2015-12-05 15:11
@pinae Should be fixed in HEAD. Confirmed?

**Closed as completed** 2015-12-05 15:11 UTC
Labels: bug
